#!/usr/bin/env python3
"""Derive the 8.86B / 8-GPU configs from the 1B / 1-GPU ones.

    python3 pretraining/configs/make_scaled_configs.py

Generated by a script rather than hand-copied so the diff against the 1B run is
auditable and re-derivable: the substitution table below IS the specification of
what "the same experiment, scaled up" means.

THE ONE RULE
------------
`global_train_batch_size` is NOT touched. It changes the optimisation
trajectory, so raising it would mean the 1B and 8.86B runs differ in two
variables at once -- budget and batch size -- which is exactly the confound this
study exists to remove. Throughput on 80GB cards comes from
`device_train_microbatch_size` instead, which only changes how many gradient
accumulation passes a step is split into and is mathematically identical.

THE BUDGET
----------
TinyGSM is a finite 2.665B-token corpus (1,301,155 usable blocks after the
2,000-block holdout). The 30% group cannot exceed it without repeating data:

    max blocks = 1,301,155 / 0.30 = 4,337,183

4,326,400 is chosen just under that. It is divisible by 256 (so the run ends on
a whole step) and by 20 (so 15% and 30% land on exact integers -- the 1B run had
a 207,482/207,481 off-by-one that this avoids), and it leaves 3,235 blocks of
slack against re-tokenisation drift on a different machine.
"""
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent

TOTAL_BLOCKS = 4_326_400
SEQ_LEN = 2048
GLOBAL_BATCH = 256                             # locked
TOTAL_TOKENS = TOTAL_BLOCKS * SEQ_LEN          # 8,860,467,200
STEPS = TOTAL_BLOCKS // GLOBAL_BATCH           # 16,900
WARMUP = round(100 / 1907 * STEPS)             # keep the 1B run's 5.24% fraction

BANNER = f"""\
# ==============================================================================
# GENERATED by pretraining/configs/make_scaled_configs.py -- do not hand-edit.
#
# This is the 1B config scaled to {TOTAL_TOKENS:,} tokens ({TOTAL_BLOCKS:,}
# blocks) on 8 GPUs. The ONLY scientific variable changed against the 1B run is
# the token budget. Everything that would alter the optimisation trajectory --
# global_train_batch_size above all -- is identical.
#
#   DO NOT raise global_train_batch_size to "use the GPUs better". It is 256 and
#   must stay 256. Use device_train_microbatch_size for throughput; gradient
#   accumulation makes it mathematically equivalent.
#
#   DO NOT raise the budget past 4,337,183 blocks. The 30% group would need more
#   TinyGSM than exists and would have to repeat data.
# ==============================================================================
"""

# (regex, replacement, human description). Each must match exactly once.
SUBS = [
    (r"^run_name: (OLMo-150M-tg\d+)$", r"run_name: \1-8b",
     "distinct run name so checkpoints and wandb runs do not collide with 1B"),

    (r"^max_duration: 1e9T$", f"max_duration: {TOTAL_TOKENS}T",
     f"token budget 1e9 -> {TOTAL_TOKENS:,}"),

    (r"^stop_at: 1907$", f"stop_at: {STEPS}",
     f"{TOTAL_BLOCKS:,} blocks / {GLOBAL_BATCH} = {STEPS:,} steps"),

    (r"^  t_warmup: 100$", f"  t_warmup: {WARMUP}",
     f"held at 5.24% of total steps, as in the 1B run ({WARMUP}/{STEPS})"),

    (r"^device_train_microbatch_size: 8$", "device_train_microbatch_size: 32",
     "8 was a 24GB limit. 256/8 GPUs = 32 per device, so this is one pass, "
     "no accumulation. Math-neutral: lower it if the 80GB card OOMs."),

    (r"^save_interval: 500$", "save_interval: 1000",
     "~7 min of wall clock on 8 GPUs -- frequent, because a borrowed machine "
     "can be reclaimed and only whole checkpoints survive"),

    (r"^save_interval_unsharded: 1000$", "save_interval_unsharded: 4000",
     "bookkeeping only"),

    (r"^eval_interval: 200$", "eval_interval: 800",
     "held-out loss curve, same ~8.9x scaling as everything else"),
]


def main() -> int:
    failures = []
    for group in ("tg00", "tg15", "tg30"):
        src = HERE / f"RL-150M-{group}.yaml"
        dst = HERE / f"RL-150M-{group}-8b.yaml"
        if not src.exists():
            failures.append(f"{src.name}: missing"); continue

        text = src.read_text()
        for pattern, repl, why in SUBS:
            text, n = re.subn(pattern, repl, text, flags=re.M)
            if n != 1:
                failures.append(f"{src.name}: {pattern!r} matched {n} times, expected 1")

        # Refuse to emit a config that silently changed the one thing that matters.
        if not re.search(rf"^global_train_batch_size: {GLOBAL_BATCH}$", text, re.M):
            failures.append(f"{dst.name}: global_train_batch_size is not {GLOBAL_BATCH}")

        dst.write_text(BANNER + "\n" + text)
        print(f"wrote {dst.name}")

    if failures:
        print("\nFAILED:", file=sys.stderr)
        for f in failures:
            print("  " + f, file=sys.stderr)
        return 1

    print(f"\n  budget/group : {TOTAL_TOKENS:,} tokens ({TOTAL_BLOCKS:,} blocks)")
    print(f"  steps        : {STEPS:,}  (x {GLOBAL_BATCH} x {SEQ_LEN} = {TOTAL_TOKENS:,})")
    print(f"  warmup       : {WARMUP}")
    print("\n  changes vs the 1B configs:")
    for _, _, why in SUBS:
        print(f"    - {why}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
